-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_bike
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_bike
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_bike` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `db_bike` ;

-- -----------------------------------------------------
-- Table `db_bike`.`FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bike`.`FUNCIONARIOS` (
  `idFUNCIONARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `LOGIN_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `SENHA_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `STATUS_FUNCIONARIO` VARCHAR(45) NOT NULL DEFAULT 'ATIVO',
  `FUNCAO_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `ENDERECO_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `TELEFONE_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `CPF_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `RG_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `CTPS_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `DATA_NASCIMENTO_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `SEXO_FUNCIONARIO` VARCHAR(45) NOT NULL,
  `ESCOLARIDADE_FUNCIONARIO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFUNCIONARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bike`.`VENDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bike`.`VENDAS` (
  `idVENDAS` INT NOT NULL AUTO_INCREMENT,
  `DATA_VENDA` VARCHAR(45) NOT NULL,
  `FUNCIONARIOS_idFUNCIONARIO` INT NOT NULL,
  PRIMARY KEY (`idVENDAS`),
  INDEX `fk_VENDAS_FUNCIONARIOS1_idx` (`FUNCIONARIOS_idFUNCIONARIO` ASC) VISIBLE,
  CONSTRAINT `fk_VENDAS_FUNCIONARIOS1`
    FOREIGN KEY (`FUNCIONARIOS_idFUNCIONARIO`)
    REFERENCES `db_bike`.`FUNCIONARIOS` (`idFUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_bike`.`BICICLETAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_bike`.`BICICLETAS` (
  `idBICICLETAS` INT NOT NULL AUTO_INCREMENT,
  `MARCA_BIKE` VARCHAR(45) NOT NULL,
  `MODELO_BIKE` VARCHAR(45) NOT NULL,
  `ARO_BIKE` VARCHAR(45) NOT NULL,
  `CONTEUDO_EMBALAGEM_BIKE` VARCHAR(45) NOT NULL,
  `COR_BIKE` VARCHAR(45) NOT NULL,
  `MARCHAS_BIKE` VARCHAR(45) NOT NULL,
  `QUADRO_BIKE` VARCHAR(45) NOT NULL,
  `FREIO_DIANTEIRO_BIKE` VARCHAR(45) NOT NULL,
  `FREIO_TRASEIRO_BIKE` VARCHAR(45) NOT NULL,
  `MANOPLA_BIKE` VARCHAR(45) NOT NULL,
  `SELIM_BIKE` VARCHAR(45) NOT NULL,
  `PEDAL_BIKE` VARCHAR(45) NOT NULL,
  `FILA_COMPRA_BIKE` VARCHAR(45) NOT NULL DEFAULT 'N',
  `FOTO_BIKE` VARCHAR(45) NOT NULL,
  `VENDAS_idVENDAS` INT NOT NULL,
  PRIMARY KEY (`idBICICLETAS`),
  INDEX `fk_BICICLETAS_VENDAS1_idx` (`VENDAS_idVENDAS` ASC) VISIBLE,
  CONSTRAINT `fk_BICICLETAS_VENDAS1`
    FOREIGN KEY (`VENDAS_idVENDAS`)
    REFERENCES `db_bike`.`VENDAS` (`idVENDAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
